version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0

    working_directory: ~/repo

    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "sync.js" }}
      - run:
          name: install-node-fetch
          command: 'sudo npm install node-fetch --save'
          
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "sync.js" }}

      - run: node sync.js
